ALTER TABLE creator_profiles
    ADD COLUMN IF NOT EXISTS location_city VARCHAR(150),
    ADD COLUMN IF NOT EXISTS location_country VARCHAR(100),
    ADD COLUMN IF NOT EXISTS location_lat DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS location_lng DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS timezone_id VARCHAR(80),
    ADD COLUMN IF NOT EXISTS languages VARCHAR(255),
    ADD COLUMN IF NOT EXISTS cta_label VARCHAR(100),
    ADD COLUMN IF NOT EXISTS cta_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS contact_address VARCHAR(300),
    ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS contact_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS availability_hours VARCHAR(200);
